# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of this app. Must be unique within a project.
name: "beacon"

# The runtime the application uses.
type: "ruby:2.6"

# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
  database: 'db:postgresql'
  redis: "redis:redis"

# The size of the persistent disk of the application (in MB).
disk: 1024

# Set environment variables to adjust how Rails will run.
variables:
  env:
    RAILS_ENV: 'production'
    RAILS_LOG_TO_STDOUT: true
    BUNDLE_ERROR_ON_STDERR: 1
    RAILS_TMP: /tmp
    EXECJS_RUNTIME: 'Node'

# The 'mounts' describe writable, persistent filesystem mounts in the application.
mounts:
  "/log":
    source: local
    source_path: log
  "/tmp":
    source: local
    source_path: tmp

# The hooks executed at various points in the lifecycle of the application.
hooks:
  # The build hook turns what is in source control into the deployable application.
  build: |
    gem install bundler:2.0.2
    bundle install --without development test
    RAILS_ENV=production bundle exec rake assets:precompile
  # The deploy hook runs after your application has been deployed and started.
  deploy: |
    bundle exec rails db:migrate

# The configuration of the application when running.
web:
  upstream:
    socket_family: tcp
    protocol: http

  commands:
    start: 'puma -C config/puma.rb'

  locations:
    "/":
      root: "public"
      passthru: true
      allow: true
